name: yanlış Build Miatoll kvm Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential flex bison git-core libssl-dev \
            libelf-dev clang-17 llvm-17 lld-17 libncurses-dev \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            python3-minimal zip ccache

      - name: Set Toolchain Alternatives
        run: |
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 100
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/lld-17 100
          sudo update-alternatives --install /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-17-nm 100
          sudo update-alternatives --install /usr/bin/llvm-objcopy llvm-objcopy /usr/get/bin/llvm-17-objcopy 100
          sudo update-alternatives --install /usr/bin/llvm-objdump llvm-objdump /usr/bin/llvm-17-objdump 100
          sudo update-alternatives --install /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-17-strip 100
          sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-17-ar 100

      - name: Cache Setup
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/ccache
          key: ${{ runner.os }}-kernel-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-kernel-ccache-

      - name: Prepare Environment
        run: |
          mkdir -p out
          ccache -M 5G

      - name: Configure Kernel
        run: |
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC="ccache clang" \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            LLVM=1 \
            vendor/xiaomi/atoll_defconfig efi.config
            
            make -j$(nproc --all) O=out olddefconfig

      - name: Compile Kernel
        run: |
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC="ccache clang" \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            LD=ld.lld \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            LLVM=1 \
            LLVM_IAS=1 \
            CONFIG_NO_ERROR_ON_MISMATCH=y

      - name: Archive Results
        run: |
          zip -r miatoll_boot_assets.zip out/arch/arm64/boot/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Miatoll-Kernel-Package
          path: miatoll_kvm-boot.zip
