name: Build Miatoll kvm Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential flex bison git-core libssl-dev \
            libelf-dev clang-17 llvm-17 lld-17 libncurses-dev \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            python3-minimal zip ccache

      - name: Cache Setup
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/ccache
          key: ${{ runner.os }}-kernel-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-kernel-ccache-

      - name: Prepare Environment
        run: |
          mkdir -p out
          ccache -M 5G
          # LLVM 17 araçlarını sistem yoluna zorla ekle
          echo "/usr/lib/llvm-17/bin" >> $GITHUB_PATH

      - name: Configure Kernel
        run: |
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC="ccache clang" \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            LLVM=1 \
            LLVM_IAS=1 \
            vendor/xiaomi/atoll_defconfig efi.config

      - name: Compile Kernel
        run: |
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC="ccache clang" \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            LD=ld.lld \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            LLVM=1 \
            LLVM_IAS=1 \
            CONFIG_SPECTRE_BHB=n \
            CONFIG_LTO_CLANG_NONE=y \
            CONFIG_NO_ERROR_ON_MISMATCH=y


      - name: Archive Results
        run: |
          zip -r miatoll_boot_assets.zip out/arch/arm64/boot/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Miatoll-Kernel-Package
          path: miatoll_boot_kvm.zip
